[project]
authors = [
    "Moses Oghene ( @LocalDevv )"
]
name = "db-sync-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "pymysql>=1.1.1",
    "python-dotenv>=1.1.1",
]
